management:
  endpoints:
    web:
      exposure:
        include: "beans,configprops,env,health,heapdump,info,liquibase,prometheus,scheduledtasks,threadump"

server:
  port: 8080
  error:
    include-stacktrace: always

springdoc:
  swagger-ui:
    path: /swagger

logging:
  level:
    root: INFO
    tech.paramount.cmsdq: INFO

spring:
  datasource:
    url: jdbc:mysql://db-mysql-cmsdq-reportingtool-use1-dev.crnseukk50lz.us-east-1.rds.amazonaws.com:3306/cmsdq_reportingtool?stringtype=unspecified
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  jackson:
    serialization:
      indent_output: true
  springdoc:
    swagger-ui:
      path: /swagger
